In [66]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
# 데이터
x = np.array([range(1,101), range(311,411), range(100)]).T  
y = np.array([range(101,201), range(711,811), range(100)]).T

In [67]:
x[:10]     # 첫번째 열은 +100, 두번째 열은 +400, 세번째 열은 +0, 즉 열마다 다른 규칙을 예쁜 패턴으로 가지고 잇음

array([[  1, 311,   0],
       [  2, 312,   1],
       [  3, 313,   2],
       [  4, 314,   3],
       [  5, 315,   4],
       [  6, 316,   5],
       [  7, 317,   6],
       [  8, 318,   7],
       [  9, 319,   8],
       [ 10, 320,   9]])

In [68]:
y[:10]

array([[101, 711,   0],
       [102, 712,   1],
       [103, 713,   2],
       [104, 714,   3],
       [105, 715,   4],
       [106, 716,   5],
       [107, 717,   6],
       [108, 718,   7],
       [109, 719,   8],
       [110, 720,   9]])

In [69]:
# 모델구성
model = Sequential()
model.add(Dense(5, input_dim=3)) 
model.add(Dense(8)) 
model.add(Dense(16)) 
model.add(Dense(520))
model.add(Dense(848))
model.add(Dense(5))
model.add(Dense(3)) 
# 훈련
model.compile(loss='mean_squared_error', optimizer='adam',metrics=['mse','acc'])
model.fit(x,y, epochs=50, batch_size=1)

Epoch 1/50
100/100 [==============================] - 0s 4ms/step - loss: 10067.8914 - mse: 10067.8877 - acc: 0.9900
Epoch 2/50
100/100 [==============================] - 0s 3ms/step - loss: 2.2528 - mse: 2.2528 - acc: 1.0000
Epoch 3/50
100/100 [==============================] - 0s 3ms/step - loss: 0.0012 - mse: 0.0012 - acc: 1.0000    
Epoch 4/50
100/100 [==============================] - 0s 3ms/step - loss: 0.0134 - mse: 0.0134 - acc: 1.0000
Epoch 5/50
100/100 [==============================] - 0s 3ms/step - loss: 86.4404 - mse: 86.4404 - acc: 1.0000
Epoch 6/50
100/100 [==============================] - 0s 3ms/step - loss: 1829.3488 - mse: 1829.3497 - acc: 1.0000
Epoch 7/50
100/100 [==============================] - 0s 3ms/step - loss: 20.3116 - mse: 20.3116 - acc: 1.0000
Epoch 8/50
100/100 [==============================] - 0s 3ms/step - loss: 0.0071 - mse: 0.0071 - acc: 1.0000
Epoch 9/50
100/100 [==============================] - 0s 3ms/step - loss: 6.0583e-05 - mse: 6.0584e-05 - a

학습을 할 때, 열 3개치고는 데이터가 적은 것 같다
mse의 변화 양상이 편차가 크다

In [70]:
# 평가
loss, mse, acc = model.evaluate(x, y, batch_size=1)
print("loss :", loss)
print("mse :", mse)
print("acc :", acc)

100/100 [==============================] - 0s 1ms/step
loss : 0.1834251081943512
mse : 0.18342508375644684
acc : 1.0


In [76]:
y_predict = model.predict(x)
print('y_predict 값은', np.round(y_predict))

y_predict 값은 [[101. 711.   0.]
 [102. 712.   1.]
 [103. 713.   2.]
 [104. 714.   3.]
 [105. 715.   4.]
 [106. 716.   5.]
 [107. 717.   6.]
 [108. 718.   7.]
 [109. 719.   8.]
 [110. 720.   9.]
 [111. 721.  10.]
 [112. 722.  11.]
 [113. 723.  12.]
 [114. 724.  13.]
 [115. 725.  14.]
 [116. 726.  15.]
 [117. 727.  16.]
 [118. 728.  17.]
 [119. 729.  18.]
 [120. 730.  19.]
 [121. 731.  20.]
 [122. 732.  21.]
 [123. 733.  22.]
 [124. 734.  23.]
 [125. 735.  24.]
 [126. 736.  25.]
 [127. 737.  26.]
 [128. 738.  27.]
 [129. 739.  28.]
 [130. 739.  29.]
 [131. 740.  30.]
 [132. 741.  31.]
 [133. 742.  32.]
 [134. 743.  33.]
 [135. 744.  34.]
 [136. 745.  35.]
 [137. 746.  36.]
 [138. 747.  37.]
 [139. 748.  38.]
 [140. 749.  39.]
 [141. 750.  40.]
 [142. 751.  41.]
 [143. 752.  42.]
 [144. 753.  43.]
 [145. 754.  44.]
 [146. 755.  45.]
 [147. 756.  46.]
 [148. 757.  47.]
 [149. 758.  48.]
 [150. 759.  49.]
 [151. 760.  50.]
 [152. 761.  51.]
 [153. 762.  52.]
 [154. 763.  53.]
 [155. 764.  54

In [77]:
y = np.array(range(711,811)).T

In [81]:
model = Sequential()
model.add(Dense(5, input_dim=3)) 
model.add(Dense(8)) 
model.add(Dense(16)) 
model.add(Dense(520))
model.add(Dense(848))
model.add(Dense(5))
model.add(Dense(1)) 
# 훈련
model.compile(loss='mean_squared_error', optimizer='adam',metrics=['mse','acc'])
model.fit(x,y, epochs=30, batch_size=1)

Epoch 1/30
100/100 [==============================] - 0s 4ms/step - loss: 24022.5662 - mse: 24022.5547 - acc: 0.0000e+00
Epoch 2/30
100/100 [==============================] - 0s 3ms/step - loss: 64.4189 - mse: 64.4190 - acc: 0.1300
Epoch 3/30
100/100 [==============================] - 0s 3ms/step - loss: 0.0520 - mse: 0.0520 - acc: 0.9500
Epoch 4/30
100/100 [==============================] - 0s 3ms/step - loss: 1.1785e-04 - mse: 1.1785e-04 - acc: 1.0000
Epoch 5/30
100/100 [==============================] - 0s 3ms/step - loss: 1.9078e-06 - mse: 1.9078e-06 - acc: 1.0000
Epoch 6/30
100/100 [==============================] - 0s 3ms/step - loss: 1.5013e-08 - mse: 1.5013e-08 - acc: 1.0000
Epoch 7/30
100/100 [==============================] - 0s 3ms/step - loss: 8.1956e-09 - mse: 8.1956e-09 - acc: 1.0000
Epoch 8/30
100/100 [==============================] - 0s 3ms/step - loss: 1.8179e-08 - mse: 1.8179e-08 - acc: 1.0000
Epoch 9/30
100/100 [==============================] - 0s 3ms/step - loss: 

In [82]:
loss, mse, acc = model.evaluate(x, y, batch_size=1)
y_predict = model.predict(x)
print('y_predict 값은', np.round(y_predict))
print("loss :", loss)
print("mse :", mse)
print("acc :", acc)

100/100 [==============================] - 0s 1ms/step
y_predict 값은 [[711.]
 [712.]
 [713.]
 [714.]
 [715.]
 [716.]
 [717.]
 [718.]
 [719.]
 [720.]
 [721.]
 [722.]
 [723.]
 [724.]
 [725.]
 [726.]
 [727.]
 [728.]
 [729.]
 [730.]
 [731.]
 [732.]
 [733.]
 [734.]
 [735.]
 [736.]
 [737.]
 [738.]
 [739.]
 [740.]
 [741.]
 [742.]
 [743.]
 [744.]
 [745.]
 [746.]
 [747.]
 [748.]
 [749.]
 [750.]
 [751.]
 [752.]
 [753.]
 [754.]
 [755.]
 [756.]
 [757.]
 [758.]
 [759.]
 [760.]
 [761.]
 [762.]
 [763.]
 [764.]
 [765.]
 [766.]
 [767.]
 [768.]
 [769.]
 [770.]
 [771.]
 [772.]
 [773.]
 [774.]
 [775.]
 [776.]
 [777.]
 [778.]
 [779.]
 [780.]
 [781.]
 [782.]
 [783.]
 [784.]
 [785.]
 [786.]
 [787.]
 [788.]
 [789.]
 [790.]
 [791.]
 [792.]
 [793.]
 [794.]
 [795.]
 [796.]
 [797.]
 [798.]
 [799.]
 [800.]
 [801.]
 [802.]
 [803.]
 [804.]
 [805.]
 [806.]
 [807.]
 [808.]
 [809.]
 [810.]]
loss : 4.060566425323487e-09
mse : 4.060566549668465e-09
acc : 1.0
